apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gnvdt9odd-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gnvdt9odd-dotnet-basic-gitops